--- 
- 
  become: true
  hosts: webservers
  tasks: 
    - 
      apt: 
        name: 
          - apache2
          - php
          - mysql-client
          - php-mysql
        state: present
      name: "Installing APACHE2 y PHP "
    - 
      name: "Ensure apache starts"
      service: "name=apache2 state=started enabled=yes"
- 
  become: true
  hosts: database
  tasks: 
    - 
      name: "Installing LAMP"
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-server', 'python3-pymysql','mysql-client' ]
      
    - 
      mysql_user: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        password: "{{ mysql_root_password }}"
      name: "Sets the root password"
    - 
      mysql_user: 
        host_all: true
        login_password: "{{ mysql_root_password }}"
        login_user: root
        name: ""
        state: absent
      name: "Removes all anonymous user accounts"
    - 
      mysql_db: 
        login_password: "{{ mysql_root_password }}"
        login_user: root
        name: test
        state: absent
      name: "Removes the MySQL test database"
  vars:
    mysql_root_password: "admin"
    app_user: "yane"
    http_host: "your_domain"
    http_conf: "your_domain.conf"
    http_port: "80"
    disable_default: true